chunk_size: 1000     # Number of lines per chunk (be mindful not to set this value too high, as each chunk is initially stored in memory)
workers:             # Number of concurrent workers that sort chunks (defaults to GOMAXPROCS if left empty)
